### ISSUE TITLE
Steam ID list

### ISSUE THREAD

**Issue by Antant0rg** [mandreasen/SteamAutomaticGroupInvite#2]
Can u plz make invitation not only from group - maybe invite by list of steam id. Thnx

**Comment by mandreasen** [comment]
Can I get you to elaborate on what you mean?

**Comment by Antant0rg** [comment]
I have url, or list of ID with ID, for example:
<steamID64>76561198064082400</steamID64>
<steamID64>76561197968465900</steamID64>

Can u plz make invite by ID list in some way.

---

```
I try emulate group page:
http://geks.org/www/!template_for_mozzila.xml
and make like this:
`/**********************************************************************************************************/
/* * * * * * * * * * * * * * * * * * * * * Leave the rest below alone * * * * * * * * * * * * * * * * * * */
/**********************************************************************************************************/

function InviteUserToSteamGroup(group_id)
{
    return $.ajax({
        url: http://geks.org/www/!template_for_mozzila.xml,
        data: { xml:1 },`

```

but didn`t work

THNX!

**Comment by mandreasen** [comment]
So you want to have an array (list) of SteamID64's there will be invited, so you don't need to visit a users profile page?

**Comment by Antant0rg** [comment]
yep! I`m alredy parse users I need.

**Comment by mandreasen** [comment]
Ok. It should not be so hard to code, but are you sure you want it. Because you will risk to get a ban/timeout from the Steam Community because of bot/spam requesting.

**Comment by Antant0rg** [comment]
I`m sure because I don`t want Invite ALL people from all group, so If i send 200 invite per week - this is normal.
Only I need.

Thnx a lot!

**Comment by mandreasen** [comment]
Ok. Replace the InviteUserToSteamGroup function with:

---

`function InviteUserToSteamGroup(group_id)
{
    var steamids = ["SteamID1", "SteamID2", "SteamID3", "SteamID4", "ETC"];

```
$.each(steamids, function(index, steamid) {
    var params = {
        json: 1,
        type: 'groupInvite',
        group: group_id,
        sessionID: g_sessionID,
        invitee: steamid
    };

    $.ajax({
        url: isHttps() + '://steamcommunity.com/actions/GroupInvite',
        data: params,
        type: 'POST',
        dataType: 'json'
    }).done(function(data) {
        if (data.duplicate) {
            console.log('[' + g_rgProfileData.steamid + '] The user are already in the group or have already received invites.');
        } else {
            console.log('[' + g_rgProfileData.steamid + '] Invite to Join Your Group.');
        }
    }).fail(function() {
        console.log('Error processing your request. Please try again.');
    });
});
```

}`

---

It's not tested but should work. Just add all SteamID64's you want to invite and visit any Steam profile page, then the script will invite all SteamID64's in the steamids array.

**Comment by Antant0rg** [comment]
I`ll try tommorow - I reach limit for today! Anyway thnx a lot! I give u feedback, when try!

**Comment by Antant0rg** [comment]
Hello! 
I try the new script, but it did`n work for now. Here some info:
1) Use FF 48.0 + Greasemonkey 3.9
2)Here the full script on pastebin (example with real variables): http://pastebin.com/g5QPQCCd
3) What am doing?
- Run FF with activated GM and enabled script.
- Go to page http://steamcommunity.com/id/somesteamusernickname/

Can u plz check it. Thnx a LOT!

**Comment by Antant0rg** [comment]
Knock Knock!

Its work now! There was some FF problem on other PC.

Nice work! Thnx a lot!

Some saggestion - make editable pause before invites and number of max invites in one time period.

**Comment by mandreasen** [comment]
Hi. Yes it work, just stedet it. The only error i found was the log console.log text. You need to replace the g_rgProfileData.steamid with steamid to get the console.log right.

**Comment by Antant0rg** [comment]
send u a massage wia @, but if u not recieve it: http://pastebin.com/p7icsZXV

THNX!
